CREATE TABLE IF NOT EXISTS sales (
  id SERIAL,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  quantity INT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT product_fk FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);